version: '3.8'

services:
  api:
    build: .
    container_name: addressbook_api
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__Default: "Server=db;Database=AddressBookDb;User=sa;Password=YourStrong@Password;TrustServerCertificate=True"
      Jwt__Key: "THIS_IS_A_SUPER_SECRET_KEY_123456789"
      Jwt__Issuer: "AddressBookApi"
      Jwt__Audience: "AddressBookApi"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: addressbook_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password"
    ports:
      - "1433:1433"
